## http unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework'],env) + [platform_libs] + ['z']

objs = env.Object('extension.o', ["extension.cpp"], LIBS = ALL_LIBS)
objs += env.Object('permessage_deflate.o', ["permessage_deflate.cpp"], LIBS = ALL_LIBS)
prgs = env.Program('test_extension', ["extension.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_permessage_deflate', ["permessage_deflate.o"], LIBS = ALL_LIBS)

Return('prgs')
