## Main development example
##

Import('env')
Import('boostlibs')
Import('platform_libs')
Import('tls_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['system'],env) + [platform_libs] + [tls_libs]
prgs += env.Program('echo_server_tls', ["echo_server_tls.cpp"], LIBS = ALL_LIBS)

Return('prgs')
