## http unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework'],env) + [platform_libs]

objs = env.Object('parser.o', ["parser.cpp"], LIBS = ALL_LIBS)
prgs = env.Program('test_http', ["parser.o"], LIBS = ALL_LIBS)

Return('prgs')
