language: cpp
compiler:
  - gcc
before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y libboost-chrono1.55-dev libboost-random1.55-dev libboost-regex1.55-dev libboost-system1.55-dev libboost-thread1.55-dev libboost-test1.55-dev
env:
  global:
    - BOOST_INCLUDES=/usr/include
    - BOOST_LIBS=/usr/lib/x86_64-linux-gnu
script: scons -j 2 && scons test
