## Main development example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['system'],env) + [platform_libs]
prgs += env.Program('subprotocol_server', ["subprotocol_server.cpp"], LIBS = ALL_LIBS)

Return('prgs')
