## connection unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('connection.o', ["connection.cpp"], LIBS = ALL_LIBS)
objs = env.Object('connection_tu2.o', ["connection_tu2.cpp"], LIBS = ALL_LIBS)
prgs = env.Program('test_connection', ["connection.o","connection_tu2.o"], LIBS = ALL_LIBS)

Return('prgs')
