## Main development example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['system'],env) + [platform_libs]
prgs += env.Program('external_io_service', ["external_io_service.cpp"], LIBS = ALL_LIBS)

Return('prgs')
