## processor unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework'],env) + [platform_libs] + ['z']

objs = env.Object('test_processor.o', ["processor.cpp"], LIBS = ALL_LIBS)
objs += env.Object('test_hybi13.o', ["hybi13.cpp"], LIBS = ALL_LIBS)
objs += env.Object('test_hybi08.o', ["hybi08.cpp"], LIBS = ALL_LIBS)
objs += env.Object('test_hybi07.o', ["hybi07.cpp"], LIBS = ALL_LIBS)
objs += env.Object('test_hybi00.o', ["hybi00.cpp"], LIBS = ALL_LIBS)
objs += env.Object('test_extension_permessage_compress.o', ["extension_permessage_compress.cpp"], LIBS = ALL_LIBS)

prgs = env.Program('test_processor', ["test_processor.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_hybi13', ["test_hybi13.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_hybi08', ["test_hybi08.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_hybi07', ["test_hybi07.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_hybi00', ["test_hybi00.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_extension_permessage_compress', ["test_extension_permessage_compress.o"], LIBS = ALL_LIBS + ['z'])

Return('prgs')
