## transport integration tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')
Import('tls_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs] + [tls_libs]

objs = env.Object('integration.o', ["integration.cpp"], LIBS = ALL_LIBS)
prgs = env.Program('test_integration', ["integration.o"], LIBS = ALL_LIBS)

Return('prgs')
