## echo_client example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['system'],env) + [platform_libs] + ['z']
prgs += env.Program('echo_client', ["echo_client.cpp"], LIBS = ALL_LIBS)

Return('prgs')
