## Main development example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['unit_test_framework','system','timer','chrono'],env) + [platform_libs]
prgs += env.Program('main', ["main.cpp"], LIBS = ALL_LIBS)

Return('prgs')
