## Telemetry client example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

prgs = []

ALL_LIBS = boostlibs(['system'],env) + [platform_libs]
prgs += env.Program('telemetry_client', ["telemetry_client.cpp"], LIBS = ALL_LIBS)

Return('prgs')
