## iostream transport unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

ALL_LIBS = boostlibs(['unit_test_framework'],env) + [platform_libs]

objs = env.Object('iostream_base.o', ["base.cpp"], LIBS = ALL_LIBS)
objs += env.Object('iostream_connection.o', ["connection.cpp"], LIBS = ALL_LIBS)
objs += env.Object('iostream_endpoint.o', ["endpoint.cpp"], LIBS = ALL_LIBS)
prgs = env.Program('test_iostream_base', ["iostream_base.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_iostream_connection', ["iostream_connection.o"], LIBS = ALL_LIBS)
prgs += env.Program('test_iostream_endpoint', ["iostream_endpoint.o"], LIBS = ALL_LIBS)

Return('prgs')
